### ISSUE TITLE
how to get the file named 'word_embeddings.npz' ?

### ISSUE THREAD

**Issue by wjmzjx** [BobXWu/ECRTM#1]
There is a file for word embeddings in data. 
What kind of word embedding is it？
glove? bert? word2vec?
I couldn't find any relevant description in the paper.

**Comment by bobxwu** [comment]
Please refer to
https://github.com/BobXWu/ECRTM/blob/d3ec58c43c04cfb2c1ab6104c43c729ad8851d07/ECRTM/preprocess/preprocess.py#L207
